name: rmb-minimal
channels:
  - conda-forge
  - r
dependencies:
  - r-base=4.4.*
  - r-essentials
  - r-tidyverse
  - r-ggplot2
  - r-circlize
  - r-devtools
  - r-irkernel
  - jupyter
  - pip
  - pip:
    - rpy2
